### ISSUE TITLE
OSX: macOS 10.12 deprecation warnings

### ISSUE THREAD

**Issue by nlguillemot** [emoon/minifb#11]
When compiling on OSX, I get a bunch of warnings like:

```warning: 'NSKeyDown' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]```

I don't know enough about OSX/Cocoa dev to easily fix this. It's just a warning, so not a show stopper.

**Comment by emoon** [comment]
Fixed in https://github.com/emoon/minifb/pull/13
