### ISSUE TITLE
Segault on Android

### ISSUE THREAD

**Issue by Jomy10** [emoon/minifb#111]
I tried running the android test, but this segfaulted at the following line:
https://github.com/emoon/minifb/blob/37776c0e947f55345c7777ab1925b1a751abb9ee/src/MiniFB_internal.c#L67

**Emulator details:**
Device: Pixel 6 Pro
API Level: 33
Resolution: 1440 x 3120
dpi: 412 x 892
ABI list: x86_64, arm64-v8a
Available storage: 4,942 MB

<details>
  <summary>Properties</summary>
Properties
avd.ini.displayname              Pixel 6 Pro API 33
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6_Pro_API_33
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     2
hw.device.hash2                  MD5:a8abfd3536f3d35e4ba2041a7b99f40e
hw.device.manufacturer           Google
hw.device.name                   pixel_6_pro
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      host
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   560
hw.lcd.height                    3120
hw.lcd.width                     1440
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         33
image.sysdir.1                   system-images/android-33/google_apis/x86_64/
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      384
</details>

My desktop:
macBook Air 2018
Intel CPU (1,6 GHz i5)
OS: macOS 13.4

**Comment by Darky-Lucera** [comment]
Now the problem is solved.

Thank you very much for the feedback.
