### ISSUE TITLE
Error compiling on MacOS Ventura

### ISSUE THREAD

**Issue by simplyrohan** [emoon/minifb#113]
Hello! I am very new to C/C++, so please forgive my lack of knowledge here. I am trying to use this library in an include folder, using the following build command

```bash
g++ -I include main.cpp
```

However, I am blasted with 11 errors, all of them caused by the same thing;
```bash
error: no member named 'bind' in namespace 'std'; did you mean 'rand'?
```

After some ~~googleing~~ research, I need to have a g++ version greater than 11. Quickly checking my version with `g++ -dumpversion `, shows that I am on g++ 14.
I am drawing a blank here, and because I'm so new, I don't know how I can debug this. Thanks for your help!

(README.md recommends using CMake, but I haven't the slightest clue how to use that...)

**Comment by emoon** [comment]
The readme details how to use CMake so please use that instead.

There is a macOS specific section here https://github.com/emoon/minifb#macos-x

There are several ways to install cmake on macOS, one is to install brew (which is useful in general on macOS) and then run `brew install cmake`

**Comment by simplyrohan** [comment]
Thank you for the response. I built with CMake and then generated `libminifb.a`. I tried linking it to my main.cpp with
```bash
g++ -L. -lminifb main.cpp 
```
Although g++ seems to ignore the file and can't find the library
```
main.cpp:1:10: fatal error: 'MiniFB.h' file not found
#include "MiniFB.h"
         ^~~~~~~~~~
1 error generated.
```

Not sure why this would be, as I moved `libminifb.a` to the same path I am running the command from. Any idea why that might be? 

Sorry if these questions are obvious, I'm pretty new to C++ and I'm using it for a very specific project (hence why this is the first library I have ever used)

**Comment by emoon** [comment]
You also need to use a -I/path/to/include (i.e the path to the include directory in minifb)

**Comment by emoon** [comment]
Did this work?

**Comment by simplyrohan** [comment]
Sorry for the late response. I finally managed to link it, but the old error of
```
error: no member named 'bind' in namespace 'std'; did you mean 'rand'?
```
persisted...

When I then add the `-std=c++14` to build with C++14, I got a new error
```
ld: symbol(s) not found for architecture arm64
```

I think it has something to do with me using MacOS Ventura but I'm not sure...

**Comment by emoon** [comment]
I really don't recommend that you build manually. But here are the steps I took:

Assume you have a directory that looks like this
```
minifb - minifb code in here
test.cpp - your test code
```
First build minifb (you have already done this but the instructions looks something like this
```
cd minifb && mkdir build && cd build && cmake .. -DUSE_METAL_API=ON && make -j8
```
After this minifb has been built. 

Create a cpp file that only has a single line
```C++
int main() { return 0; }
```
With the directory listing above (outside of the minifb directory)
```
g++ test.cpp -o test
```
Run `./test` and make sure it works
```
g++ -std=c++14 test.cpp -o test 
```
Run `./test` and make sure it works
```
Run and make sure
```
g++ -std=c++14 test.cpp -Iminifb/include -Lminifb/build -lminifb -framework Cocoa -framework MetalKit -framework Metal -o test
```
Run the ./test again and make sure it just starts and exits.
Change your cpp code to contain the following
```C++
#include <MiniFB.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

static uint32_t g_width  = 800;
static uint32_t g_height = 600;
static uint32_t* g_buffer = 0x0;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

void resize(struct mfb_window* window, int width, int height) {
    (void) window;
    g_width  = width;
    g_height = height;
    g_buffer = (uint32_t*)realloc(g_buffer, g_width * g_height * 4);
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

int main() {
    uint32_t i, noise, carry, seed = 0xbeef;

    struct mfb_window* window = mfb_open_ex("Noise Test", g_width, g_height, WF_RESIZABLE);
    if (!window)
        return 0;

    g_buffer = (uint32_t*)malloc(g_width * g_height * 4);
    mfb_set_resize_callback(window, resize);

    mfb_set_viewport(window, 50, 50, g_width - 50 - 50, g_height - 50 - 50);
    resize(window, g_width - 100, g_height - 100);  // to resize buffer

    mfb_update_state state;
    do {
        for (i = 0; i < g_width * g_height; ++i) {
            noise = seed;
            noise >>= 3;
            noise ^= seed;
            carry = noise & 1;
            noise >>= 1;
            seed >>= 1;
            seed |= (carry << 30);
            noise &= 0xFF;
            g_buffer[i] = MFB_ARGB(0xff, noise, noise, noise);
        }

        state = mfb_update_ex(window, g_buffer, g_width, g_height);
        if (state != STATE_OK) {
            window = 0x0;
            break;
        }
    } while(mfb_wait_sync(window));

    return 0;
}
```
Run the compile commandline again:
```
g++ -std=c++14 test.cpp -Iminifb/include -Lminifb/build -lminifb -framework Cocoa -framework MetalKit -framework Metal -o test
```
Run `./test` and you should have a window running a test program.

This was all tested on M1

**Comment by simplyrohan** [comment]
Thank you so much. Just compy-pasting those commands has worked. I did something wrong in building the library. This library works great, and it's just what I need for my project
