### ISSUE TITLE
Window always renders white on Windows 11 in release  build. 

### ISSUE THREAD

**Issue by neildanson** [emoon/minifb#115]
I appreciate this may not be an issue with minifb (Windows versions, Graphics driver versions) - but its pretty much my only dependency. 

Everything displays correctly in debug builds. Same code works fine in both release & debug on M1 mac. 

Any of the examples exhibit this. 

Main things I can think of that may impact?

rustc 1.79.0-nightly (ccfcd950b 2024-04-15)

Nvidia 3080, game ready driver 552.22 (april 16 2024)

Edition	Windows 11 Pro
Version	23H2
Installed on	‎06/‎10/‎2022
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0

I had a small application that was fine from 1 month ago, no changes in code (probably a windows update and a rustup update).

**Comment by emoon** [comment]
Hey, I assume you are talking about the Rust version of minifb here? (i.e https://github.com/emoon/rust_minifb)

**Comment by neildanson** [comment]
Ah yes. I'll move over there 🤦‍♂️

**Comment by neildanson** [comment]
Closing and moved to https://github.com/emoon/rust_minifb/issues/351
