### ISSUE TITLE
update is broken on macOS Mojave

### ISSUE THREAD

**Issue by emoon** [emoon/minifb#16]
Same issue as https://github.com/emoon/rust_minifb/issues/57

**Comment by Darky-Lucera** [comment]
Are there some news on this issue?

**Comment by emoon** [comment]
Yes, the latest version should work just fine.

**Comment by Darky-Lucera** [comment]
It's still frozen. Only the first frame is painted and it is not updated anymore.

**Comment by emoon** [comment]
Oh, I only fixed this in https://github.com/emoon/rust_minifb I will have to port the code over

**Comment by Darky-Lucera** [comment]
Thanks a lot!

**Comment by emoon** [comment]
Of course if you could help out with it based on the code here https://github.com/emoon/rust_minifb/commit/79608b38a27fda90407049e598d292c26b8dc9a7 (it's all ObjC as the C version is) that would help me a lot.

**Comment by Darky-Lucera** [comment]
Ok, I will take a look. I was yesterday trying to fix it without getting it. The guys from Apple have really broken the API.

**Comment by emoon** [comment]
Yeah :( In this case I just decided to use the Metal API for it as it also makes it faster. The problem is that it won't work on GPUs that doesn't support Metal but pretty much every GPU from 2012 supports it's so I figured it was it was a good enough trade off as I didn't want to support the old path at the same time.

**Comment by Darky-Lucera** [comment]
OK, it works now but I got a segmentation fault and I want to take a second look but now I must go out. I will try during the weekend

**Comment by emoon** [comment]
Awesome! Thanks for looking into this :)

**Comment by janderland** [comment]
Hey, just pinging to see if any work has be done on this. I understand if you haven't had time. I am eager to try out this library for some low-level generative art. Looking forward to possible fixes.

**Comment by Darky-Lucera** [comment]
The library is fixed for mojave now. 
Also I added input events for all platforms that are waiting for review. I want to unify the files in this last change

**Comment by emoon** [comment]
Sorry I haven't got around for the review yet :( I hope to get it done this weekend for sure.

**Comment by Darky-Lucera** [comment]
Don't worry Daniel. We all are busy.
In any case, janderland, the mojave fix is already merged. So, just compile and run the noise sample.

**Comment by Darky-Lucera** [comment]
could we close this issue?

**Comment by emoon** [comment]
Yeah lets do it!
