### ISSUE TITLE
Problem compiling on arm with 1.6

### ISSUE THREAD

**Issue by petevine** [emoon/minifb#2]
Due to this [breakage](https://github.com/rust-lang/rust/issues/29867) the crate doesn't compile on arm.

````
Compiling minifb v0.1.0 (https://github.com/emoon/rust_minifb.git#858b07f5)
/home/odroid/.cargo/git/checkouts/rust_minifb-65b6a7c68ef60bd2/master/src/lib.rs:38:24: 38:34 error: mismatched types:
 expected `*const i8`,
    found `*const u8`
(expected i8,
    found u8) [E0308]
/home/odroid/.cargo/git/checkouts/rust_minifb-65b6a7c68ef60bd2/master/src/lib.rs:38         ret = mfb_open(s.as_ptr(), width as c_int, height as c_int);
                                                                                                           ^~~~~~~~~~
/home/odroid/.cargo/git/checkouts/rust_minifb-65b6a7c68ef60bd2/master/src/lib.rs:38:24: 38:34 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
````

I tried to fix it with a simple hack `s.as_ptr() as *const _` but it ends in a segfault.
Using `std::mem:transmute` seems to segfault as well so you'll have to look into it yourself :)

(I think I had it working from within [rust64](https://github.com/kondrak/rust64) a few months ago using 1.5)

**Comment by emoon** [comment]
First. This is the C version of the lib, the Rust version is over here: https://github.com/emoon/rust_minifb

Second as stated on the readme:

"Currently Mac, Windows has been Linux has been tested which are the supported platforms for now."

**Comment by petevine** [comment]
Meaning? Is linux supported or not?

**Comment by emoon** [comment]
Linux has been tested and worked for me at least (requires that you run X though, I tested on Ubuntu)

**Comment by petevine** [comment]
If linux is not a has been then we're good to go :)

**Comment by emoon** [comment]
I noticed that the text I based was very confusing (fixed now) so yes, Linux should work fine (running under X) though I haven't actually tested it on ARM.

**Comment by petevine** [comment]
There's no problem on x86 indeed and I may recall seeing it run on arm a few months ago, before libc 0.2 and the libstd breakage in 1.6.

Should the casts I'd tried lead to a segfault or is it something else?

**Comment by petevine** [comment]
I'll close it here and start a new issue in the rust repo. Alternatively, if allowed on github, you could move the issue. Thx.

**Comment by petevine** [comment]
Hmm, is it safe to use two different libc crates in the same project? Maybe that is the root cause of the resulting segfault that doesn't happen on x86.

````
Compiling libc v0.2.2
Compiling libc v0.1.12
````

**Comment by emoon** [comment]
Please comment here instead https://github.com/emoon/rust_minifb/issues/1
