### ISSUE TITLE
Failed to compile on Windows

### ISSUE THREAD

**Issue by ukabuer** [emoon/minifb#22]
It seems that the macro `GWL_USERDATA` in `src\windows\WinMiniFB.c(22)` is not defined.
And It can compiles if I change it to `GWLP_USERDATA`.

My environment:
- Windows 10 (1903)
- CMake 3.14.5
- Visual Studio 2017 with Windows 10 SDK (10.0.17763.0).

**Comment by emoon** [comment]
Maybe this is related to your changes @Darky-Lucera

**Comment by Darky-Lucera** [comment]
This macro is defined in winuser.h but it seems that it is undef for Win64:

```
#define GWL_USERDATA        (-21)

#ifdef _WIN64

#undef GWL_USERDATA

#endif /* _WIN64 */

#define GWLP_USERDATA       (-21)

```

I will change it for the next update that it is almost done.

Sorry for the inconveniences.
