### ISSUE TITLE
No way to determine mouse position?

### ISSUE THREAD

**Issue by CalebKierum** [emoon/minifb#24]
Based on the docs (albeit for the rust version) linked below it looks like there should be the ability to get the mouse position using get_mouse_pos. Now it would appear there is no such method.

https://docs.rs/minifb/0.10.5/minifb/struct.Window.html#method.get_mouse_pos

**Comment by emoon** [comment]
Yeah currently the Rust version has more features than the C version. I never intended to add as much functionality to the Rust version as it currently has so many things has never made it back to the C version.

**Comment by Darky-Lucera** [comment]
You can use mfb_get_mouse_x and mfb_get_mouse_y
