### ISSUE TITLE
Linker dependencies

### ISSUE THREAD

**Issue by nolo18** [emoon/minifb#25]
I love this little thing, but as I can see in CMakeLists.txt, libraries such as X11 or Metal Framework have to be linked in your executable, so...
Why do you decide to do in that way rather than link them directly to minifb library?, I mean, why doesn't exist something like:
`target_link_libraries (minifb X11)`
in CMakeLists.txt.
Also would be interesting, to include
`target_include_directories(minifb ${CMAKE_CURRENT_SOURCE_DIR}/include)`
so you can use it directly like a sub-directory into your cmake based project with all of its benefits.
Also I notice in de README.md example code that in the call to mfb_update() function the pointer window parameter is missing.

**Comment by Darky-Lucera** [comment]
done
