### ISSUE TITLE
Colors in Windows 7 wrong

### ISSUE THREAD

**Issue by jesko42** [emoon/minifb#3]
It appears that the colors are wrong in the current release. If I set 0x00ff0000 as a color I get red (correct), but 0x00ffff00 is not yellow (it's still red).
Bugfix: change **s_bitmapInfo** entry from **BITFIELDS** to **BI_RGB**:

s_bitmapInfo.bmiHeader.biCompression = BI_RGB;

**Comment by emoon** [comment]
Thanks! Will fix.

**Comment by nlguillemot** [comment]
Is this fixed?

**Comment by nlguillemot** [comment]
seems like BGRA colors are used

**Comment by emoon** [comment]
I will investigate this again. The thing is I have pretty much the same code in my Rust version and it's used be a fair number of people (more than the C version) and I never heard any complains about it.

**Comment by nlguillemot** [comment]
I tried switching BITFIELDS to RGB and I don't see the difference, so *shrug*

**Comment by emoon** [comment]
I think we can close this one now right with your fixes @nlguillemot

**Comment by nlguillemot** [comment]
Can @jesko42 confirm if this is still an issue? If not, might as well close.

**Comment by emoon** [comment]
I will close this one for now. Please re-open if it still doesn't work for you.
