### ISSUE TITLE
Type prefixes

### ISSUE THREAD

**Issue by rxi** [emoon/minifb#31]
Although the library uses prefixes on its functions to avoid name collisions, the same isn't done for the types. Is adding the prefix to the types (eg. `Window` => `mfb_Window`) a change you would consider making or accepting as a pull request?

**Comment by emoon** [comment]
cc @Darky-Lucera

**Comment by Darky-Lucera** [comment]
Make sense. Do you have it already done?

**Comment by rxi** [comment]
I do not

**Comment by Darky-Lucera** [comment]
I wiill do
