### ISSUE TITLE
No repaint when calling both mfb_update_events and mfb_update in a loop

### ISSUE THREAD

**Issue by rxi** [emoon/minifb#32]
On windows, when using both `mfb_update_events` followed by `mfb_update` in a loop, the window doesn't appear to ever repaint and shows only black. If the call to `mfb_update_events` is omitted the window repaints like normal. The same code works as expected on linux.

**Comment by emoon** [comment]
cc @Darky-Lucera

**Comment by Darky-Lucera** [comment]
Probably because WM_PAINT is an event. Let me think if I can solve it

**Comment by Darky-Lucera** [comment]
I fix it in https://github.com/emoon/minifb/pull/33
