### ISSUE TITLE
Blank window in release mode only?

### ISSUE THREAD

**Issue by nlguillemot** [emoon/minifb#4]
I really don't understand why, but I only get a blank white window when I build this library in release mode. This is on Windows 10, 64 bit build, Visual Studio 2015.

WM_PAINT messages are coming, the code is not hanging anywhere, the data I pass in looks ok...

I really don't understand what could be going wrong.

**Comment by nlguillemot** [comment]
The mystery thickens:
In 64-bit builds, I get nothing. In 32-bit builds, I get something showing up, but the colors look washed out.

**Comment by emoon** [comment]
hum... let me investigate.

**Comment by emoon** [comment]
So it might be related to this

https://github.com/emoon/minifb/blob/master/src/windows/WinMiniFB.c#L117

The way I do in in the Rust version is to have a copy of this buffer which is of course way safer in case the user would decide to delete the buffer after running the update code.

**Comment by nlguillemot** [comment]
Mystery solved, s_bitmapInfo was accessing members bmiColors[1] and bmiColors[2] which were out of bounds. BITMAPINFO is one of those C style "flexible array" classes, so I replaced it with the typical code used for that. Going to prepare a pull request.

**Comment by emoon** [comment]
ah! thanks :)
