### ISSUE TITLE
[Julia] Window does not close in Mac

### ISSUE THREAD

**Issue by aviks** [emoon/minifb#44]
I am writing a wrapper for minifb in the Julia Programming Language. Julia is a dynamic language with its own REPL. It has an easy C ffi, so function calls in Julia forward directly to C API calls in minifb. 

So I'm using code like this 
```
function noise()
    WIDTH = 800
    HEIGHT = 600
    g_buffer = zeros(UInt32, WIDTH * HEIGHT)
    window = mfb_open_ex("Noise Test", WIDTH, HEIGHT, MiniFB.WF_RESIZABLE);
    while mfb_wait_sync(window)
       for i in 1:WIDTH * HEIGHT
             # populate g_buffer
        end
        state = mfb_update(window, g_buffer);
        if state != MiniFB.STATE_OK
            break;
        end
    end
    mfb_close(window)
end
```

And this works well. However, on the Mac, I find that the window does not close. It stays on screen, even when the function has returned. (Note that due to the REPL, the Julia process is still in memory, but the function above has returned). If I exit the process, the windows does close. And if i run another `mfb_open_ex` in the same process, the old window dissapears, and the new one comes on. 

On Windows 10, the window is closed when the function returns. 

Any ideas why this could be? 

PS: code here: https://github.com/aviks/MiniFB.jl

**Comment by emoon** [comment]
@Darky-Lucera any idea?

**Comment by aviks** [comment]
I should mention that this was compiled with `MetalKit` on SDK version `10.12`, and I was trying this on a macbook with `10.14`

**Comment by Darky-Lucera** [comment]
I was a bit busy...

Now the window closes properly using Cocoa and Metal APIs.

Please, try it now and let us know if it works.

BTW, thanks for porting MiniFB to Julia!

PD: Excuse me. I closed this issue through a commit message.

**Comment by aviks** [comment]
Thank you for the quick fix. I'm building and testing this now.

**Comment by aviks** [comment]
I have confirmed that this issue is fixed on latest master. Thanks!
