### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aviks** [emoon/minifb#45]
As you know, this library has now been wrapped for the Julia programming language. I wanted to thank you for creating and maintaining this library. The Julia community has shown a lot of interest in this library -- many developers have already integrated their packages with MiniFB. You can see the discussion here: https://discourse.julialang.org/t/build-simple-guis-with-minifb/46195. You will certainly see more of us here. 

Also worth mentioning, we build and distribute binaries of MiniFB for 13 different platforms: Win/Linux/Mac/FreeBSD, x86/x64/armv7/aarch64/power. This ensures our users do not have to have C compliers on their machines to use the library. The build recipes are here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/MiniFB/build_tarballs.jl . The resulting binaries (dll/dylib/so) can be downloaded from https://github.com/JuliaBinaryWrappers/MiniFB_jll.jl/releases/tag/MiniFB-v0.1.1%2B1

Finally, the source of the Julia package is here: https://github.com/aviks/MiniFB.jl and the documentation: https://juliahub.com/docs/MiniFB/

Please close this issue at your convinience, I just wanted to let you know what we have been up to.

**Comment by aviks** [comment]
cc: @emoon @Darky-Lucera

**Comment by emoon** [comment]
Great stuff :)
