### ISSUE TITLE
disable "Window created" message?

### ISSUE THREAD

**Issue by JeffBezanson** [emoon/minifb#46]
It would be nice to remove (or at least have a way to disable) the printed message on each window creation. It is generally not good behavior for libraries to print messages unnecessarily.

**Comment by aviks** [comment]
I don't see that in Windows or the Mac, seems to be specific to the X11 implemenation here: https://github.com/emoon/minifb/blob/dda1275bd741752d1b7cdc1ee4d9941887a1891a/src/x11/X11MiniFB.c#L195

**Comment by aviks** [comment]
Actually, that is wrong, it does display on the Mac, X11 and Wayland. Not on Windows. 

https://github.com/emoon/minifb/search?q=%22Window+created%22&unscoped_q=%22Window+created%22

I could do a PR to remove the printing, but not sure if a more sophisticated approach to logging is wanted.

**Comment by emoon** [comment]
Hey, Please do a PR to remove these.

**Comment by Darky-Lucera** [comment]
This message is for when the library has different APIs to work with:
    - Window created using Metal API
    - Window created using Cocoa API
    - Window created using Wayland API
    - Window created using X11 API

For this reason you cannot see it in Windows or iOS, because there is only one option on those OS.

If you don't like it, I can print it only in debug mode.

**Comment by aviks** [comment]
> I can print it only in debug mode.

I think that would be a great solution.

**Comment by Darky-Lucera** [comment]
done
