### ISSUE TITLE
Full-resolution on Retina displays (Mac and iOS)

### ISSUE THREAD

**Issue by drfuchs** [emoon/minifb#47]
For MacOS with a hi-dpi Retina display, and all iOS, is there a way to tell mfb_update that the buffer contains 4 times as many pixels that can be directly displayed? There seems to be some code in iOSMiniFB.m that deals with [UIScreen mainScreen].scale but it's not clear that it suffices; and there's no similar code in MacMiniFB.m.  Thanks, and apologies if this is already addressed.

**Comment by Darky-Lucera** [comment]
Could you try the new branch update_ex? (WIP)

**Comment by drfuchs** [comment]
Thanks; I was just reading the code and running the demos to see if miniFB would be a suitable replacement for GLFW in my very bitmap-oriented project, and this was the only issue I noticed (the input_events demo reported "Input Events Test > resize: 2560, 1417" when I resized the window to fill my 5120 x 2880 iMac display). So, I'm forging ahead with my port, but it will be a day or two to get it all going, and be able to report back on your change.  BTW: in update_ex branch: noise.c:13:27: warning: unused parameter 'window'

**Comment by Darky-Lucera** [comment]
Now is merged into master. Please check it out

**Comment by drfuchs** [comment]
Works great on my retina-display macs, thanks. I created a pull request with test code, if it's wanted. I don't have non-retina / non-mac hardware, so couldn't test those environments.
