### ISSUE TITLE
Segfault on updating closed window [Linux/X11]

### ISSUE THREAD

**Issue by aviks** [emoon/minifb#48]
On calling `mfb_update` once after closing a window, `STATE_EXIT` is returned. On calling `mfb_update` a second time, a segfault is thrown, which looks possibly like a double free. 

Replication using Julia is below. C code looks very similar. 

```
julia> using MiniFB

julia> window = mfb_open("Noise Test", 300, 400);
Window created using X11 API

julia> g_buffer = zeros(UInt32, 300 * 400);

julia> mfb_update(window, g_buffer)
STATE_OK::mfb_update_state = 0

julia> mfb_close(window)

julia> mfb_update(window, g_buffer)
STATE_EXIT::mfb_update_state = -1

julia> mfb_update(window, g_buffer)
signal (11): Segmentation fault
in expression starting at REPL[10]:1
__libc_free at /build/glibc-2ORdQG/glibc-2.27/malloc/malloc.c:3098
destroy_window_data at /home/aviks/.julia/artifacts/94a1e8c638cfe92322b13b5657c82978c19230b4/lib/libminifb.so (unknown line)
mfb_update at /home/aviks/.julia/artifacts/94a1e8c638cfe92322b13b5657c82978c19230b4/lib/libminifb.so
```

This is with the X11 backend on Linux. On Windows, multiple `mfb_update`s on a closed window returns `STATE_EXIT` correctly.

**Comment by Darky-Lucera** [comment]
By design when a window is closed we free the memory associated with that window. This is the reason you get a segfault, because when you are calling mfb_update with an invalid pointer.

Logically we have a contract by which when the user calls a MiniFB function with a window pointer, this must be a valid pointer.

**Comment by aviks** [comment]
> we have a contract by which when the user calls a MiniFB function with a window pointer, this must be a valid pointer.

That is fair. but is there a way for the user to check if the pointer is valid before calling such a function? Is it possible to have an `is_open(window)` function that the user can check before calling other functions?

**Comment by Darky-Lucera** [comment]
The window is not closed, it is destroyed.

The user would do something like this:
```c
    state = mfb_update_ex(buffer, 800, 600);
    if (state < 0) {
        window = NULL;
        break;
    }
```
That is quite easy.

For the user not to do this, the library should maintain a map (list, vector, ...) of destroyed window pointers, but when the library must free this data?

We could do it, but does it make sense?

**Comment by aviks** [comment]
Hmnn yeah, that makes sense. The use case came from the fact that julia can make asynchronous calls (single threaded, but still async) but with some effort that code can be written to be serialised.
