### ISSUE TITLE
is_open function

### ISSUE THREAD

**Issue by aviks** [emoon/minifb#49]
While the segfault in #48 should probably be fixed, a possible mitigation might have been the existence of an `is_open(window)` function. That will prevent calling `mfb_update` on closed windows. 

It looks like the minifb_rust has an `is_open` function, so it may be useful to have it here as well?

**Comment by Darky-Lucera** [comment]
By design when a window is closed we free the memory associated with that window. This is the reason you get a segfault, because when you are calling mfb_update with an invalid pointer.
