### ISSUE TITLE
real width and height with no dpi correction

### ISSUE THREAD

**Issue by NikLeberg** [emoon/minifb#52]
Hey there,

very nice little library! Thanks for your work.

The width & height do not match the pixels on screen.

I'm experimenting a bit and was curious to know, if there is a straight forward way to let the width and height one initializes the mfb with, correspond to the actual pixels that the display is displaying. As I could see in the code, it gets corrected with the specific display dpi. In theory thats really nice, so the window is more or less the same size on all displays.
Is there a flag or function to disable this? Or maybe mention in the readme that this scaling is gonna happen?

Just as a suggestion.

For my experiments on windows I've rewritten lines 432 & 432 of [`mfb_open_ex()`](https://github.com/emoon/minifb/blob/17df5633cddd0e3e16b512ef441f847bc468f05b/src/windows/WinMiniFB.c#L423) to be:
```
        rect.right  = (LONG) width;
        rect.bottom = (LONG) height;
```
But I'm not sure if this breaks some other things down the line.

Have a great day!
Nik

**Comment by Darky-Lucera** [comment]
Hello,

excuse me for the long delay. Here you can test an experimental branch to do this: https://github.com/emoon/minifb/tree/do_not_dpi_scale

Only works for Windows at this point

**Comment by ragekit** [comment]
Checking this because I need it too. Wondering : why not make get_monitor_scale set scale_x and scale_y to 1 if WF_DO_NOT_DPI_SCALE is set ?
