### ISSUE TITLE
compiler flags forced in CMakeLists.txt are GCC-specific, warned and ignored in clang

### ISSUE THREAD

**Issue by bradgrantham** [emoon/minifb#56]
On my Mac I get `warning: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]`.  I'm not certain but it looks like "cast-function-type" is GCC-specific.

I don't know if "bad-function-cast" is the right option for clang (as suggested) and my CMake-fu isn't strong enough to recommend a change to emit a different option on clang, I apologize.

**Comment by Darky-Lucera** [comment]
now is fixed!
