### ISSUE TITLE
What is the difference between keyboard callback and char input callback ?

### ISSUE THREAD

**Issue by amirouche** [emoon/minifb#59]
I read the callbacks take different arguments, but I am not sure which one to use.

**Comment by Darky-Lucera** [comment]
As an example, look at this:

char input:
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-char
https://docs.microsoft.com/en-us/windows/win32/menurc/wm-syschar
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-unichar

keyboard:
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-keydown
https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-syskeydown
and the up events

**Comment by amirouche** [comment]
I do not understand windows doc. 

Maybe relating to web browser API can help me. Anyway, I will test and read the code, and report back.

**Comment by Darky-Lucera** [comment]
Well now is a little bit better. With char_input you can get the Unicode value, while with the keyboard you can get the key code. 
With the Unicode, you will be able to differentiate 'a' from 'A', get international characters like ñ, Ç, ¿, ¡, or get compound characters like Á, é, Ì, ò, û (this last only on MacOS X and Windows at this moment)
