### ISSUE TITLE
Suggestion: #include "MiniFB.h" instead of <MiniFB.h>

### ISSUE THREAD

**Issue by nlguillemot** [emoon/minifb#6]
At least with Visual Studio, including <MiniFB.h> inside WinMiniFB.c requires MiniFB's path to be put in the include directory list, even if MiniFB.h is in the same directory as WinMiniFB.c.

I was lazy and dropped all the files into the same directory, so I had to switch to include "MiniFB.h", note the with double quotes instead of angle braces.

I think using double quotes still looks at the include directory list if it can't find a local file with the name, so I guess that approach is more compatible. Therefore, I suggest replacing all includes of <MiniFB.h> with "MiniFB.h".

**Comment by emoon** [comment]
Sure, that is fine. Can you do another PR? :)
