### ISSUE TITLE
Consider integrating TinyGL?

### ISSUE THREAD

**Issue by gek169** [emoon/minifb#61]
Perfect project for integrating with TinyGL, a software GL 1.1 implementation that runs faster than Mesa.
https://github.com/C-Chads/tinygl

**Comment by emoon** [comment]
Hi. I don't think it makes sense to integrate such library as minifb provides a window and a way to render into it. How the actual rendering is done should be all on th user side.

**Comment by gek169** [comment]
alrighty!
