### ISSUE TITLE
Mouse Y is inverted on Mac

### ISSUE THREAD

**Issue by aduros** [emoon/minifb#66]
The Y values of the mouse (using `mfb_get_mouse_y`) seem to be inverted. It looks like 0 = the bottom of the window, where 0 should = the top of the window.

**Comment by Darky-Lucera** [comment]
There are some systems where the Y coordinate starts at the bottom of the window and others where the Y coordinate starts at the top, but you are right. For coherency, we have to invert it. It is done in the last commit.

In any case, as this change breaks compatibility, I added an option to CMake to keep the old behavior:

```
mkdir build
cd build
cmake .. -DUSE_INVERTED_Y_ON_MACOS=ON
```

Please check it out and let me know if you find any problems.

**Comment by aduros** [comment]
Looks great, thanks! I haven't tested it yet, but I'll let you know if there's anything unexpected.
