### ISSUE TITLE
a meet by chance bug.

### ISSUE THREAD

**Issue by Rainbowcatm** [emoon/minifb#80]
whn i us minifb finish code a example.  some magic things happened. lol...
i can us the mouse check window and nothing apear.
but if i us keyboard anyone key,the window will stuck.
i can't even turn it off. 
last, i have to kill explorer and reboot.

**Comment by Rainbowcatm** [comment]
i guess its a focus or keyboard related bug.

**Comment by Rainbowcatm** [comment]
expecting you reply. thanks.

**Comment by Darky-Lucera** [comment]
I just checked all the examples and everything works fine.

Are all the examples hanging on your computer?
What operating system are you using?
What compiler are you using? (exact version)
Are you declaring any MiniFB CMake variable?

**Comment by Rainbowcatm** [comment]
well...it work normally now.after compute reboot and update compile and umm....so on.its magical...thank you.

**Comment by Rainbowcatm** [comment]
you can close issue.and thanks once agin.
