### ISSUE TITLE
Scaling for WF_FULLSCREEN window (on Windows)

### ISSUE THREAD

**Issue by bsutherland** [emoon/minifb#91]
If I create a window with `WF_FULLSCREEN`, the pixel buffer seems to be sized according to the desktop resolution, not the width and height arguments. So the content is small and in the top left corner, instead of filling the screen. It is proportional though.

If I create a window with `WF_FULLSCREEN_DESKTOP`, the pixel buffer seems to be correctly sized and fills the window, but the window size isn't proportional to the frame buffer, so the content is stretched.

It would be nice to be able to programmatically resize a window, and/or create a full-screen window with the content scaled (preferably proportionally, with black bars if necessary).

**Comment by Darky-Lucera** [comment]
I just upload an example to show how to control the viewport size. It calculates the correct viewport size to proportionally scale the input buffer adding black bars when necessary.

In the example, my native resolution is 1920x1080.

```
Type Width Height
0:   =     =
1:   =     <
2:   =     >
3:   <     =
4:   <     <
5:   <     >
6:   >     = 
7:   >     <
8:   >     >
```

Examples Type: 
```
0: 1920x1080 -> x: 0,    y: 0,   width: 1920, height: 1080
1: 1920x1000 -> x: 0,    y: 40,  width: 1920, height: 1000
2: 1920x2000 -> x: 442,  y: 0,   width: 1036, height: 1080
3: 1000x1080 -> x: 460,  y: 0,   width: 1000, height: 1080
4: 800x600   -> x: 240,  y: 0,   width: 1439, height: 1080
4: 800x400   -> x: 0,    y: 60,  width: 1920, height: 960
5: 1000x2000 -> x: 700,  y: 0,   width: 519,  height: 1080
6: 2500x1080 -> x: 0,    y: 125, width: 1920, height: 829
7: 3000x1000 -> x: x: 0, y: 220, width: 1920, height: 640
8: 3000x1500 -> x: 0,    y: 60,  width: 1920, height: 960
8: 3000x3000 -> x: 420,  y: 0,   width: 1080, height: 1080
```

I hope it will be helpful.

PD: You can also control viewport on resize callback

**Comment by bsutherland** [comment]
Thank you, https://github.com/emoon/minifb/commit/d17242bb2dad139dfdf9726eea59c218bd0c9852 is exactly what I was looking for! Maybe this function could be part of the library?

**Comment by Darky-Lucera** [comment]
Finally, I have had time to add it. It's called: mfb_set_viewport_best_fit. The width & height params are the original user framebuffer size.
The example fullscreen is also updated.

Do you know that you can also modify your framebuffer size?
Just realloc it and call mfb_update_ex with the new size instead of mfb_update

**Comment by bsutherland** [comment]
Thank you!
