### ISSUE TITLE
Enhancement: WebAssemby support?

### ISSUE THREAD

**Issue by axiys** [emoon/minifb#93]
Has anyone tried to get minifb working via Emscripten (generate WebAssembly)? I am thinking of adding support for it for my simulation platform in minifb. Are you all ok for some pull requests with appropriate flags and demos?

It may be possible and then support not only framebuffers but most of the keyboard and mouse events.

Example: https://wasmbyexample.dev/examples/reading-and-writing-graphics/reading-and-writing-graphics.go.en-us.html

**Comment by Darky-Lucera** [comment]
It will be nice having support for webAssembly

**Comment by badlogic** [comment]
I went ahead and started building just this for a personal project:
https://github.com/badlogic/r96

I'm not sure what the best way would be to get this into upstream minifb. Maybe it can serve as a basis for anyone who wants to make this into a proper minifb feature :)
